[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@forge-std/=lib/forge-std/src/'
]

# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = {key = "${ETHERSCAN_API_KEY}"}

# [rpc_endpoints]
# sepolia = "${SEPOLIA_RPC_URL}"
