[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add remappings to resolve imports correctly
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Include settings to optimize Foundry workflows
[default]
evm_version = "paris" # Set to the desired EVM version (e.g., istanbul, london, paris)
optimizer = true
optimizer_runs = 200
ffi = true # Enable ffi if your tests/scripts require external calls
